### PR TITLE
Reports functionality

### PR DESCRIPTION
**Pull request by Mat203**

### CODE REVIEW

**Review by smazepaa — APPROVED** [review]
clear code and all the requirements are met

**Review by AntoninaNov — APPROVED** [review]
Great work on implementing the feature. The code is clean, adheres to the project guidelines, and passes all tests. Keep it up!

**Review by smazepaa — APPROVED** [review]
clean code and all requirements are taken into account

**Review by smazepaa — APPROVED** [review]
clear code and all requirements are met

**Pull request merged**
